spring:
  application:
    name: lorevault-cli
  main:
    web-application-type: none
  config:
    import: classpath:application-common.yml
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}
    pool:
      metrics-enabled: false

logging:
  level:
    com.lorevault: INFO
    org.springframework: WARN
    org.neo4j: WARN